//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PUNTO = 12;
  public static final int IGUAL = 13;
  public static final int CUERPO = 6;
  public static final int ERROR = 22;
  public static final int GARRA = 7;
  public static final int INICIAR = 3;
  public static final int COMA = 18;
  public static final int EOF = 0;
  public static final int BASE = 5;
  public static final int NUMERO = 21;
  public static final int REPETIR = 11;
  public static final int PARENTESIS_C = 15;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 20;
  public static final int LLAVE_C = 17;
  public static final int PARENTESIS_A = 14;
  public static final int PUNTO_COMA = 19;
  public static final int LLAVE_A = 16;
  public static final int DETENER = 4;
  public static final int CERRAR_GARRA = 10;
  public static final int VELOCIDAD = 8;
  public static final int ROBOT = 2;
  public static final int ABRIR_GARRA = 9;
  public static final String[] terminalNames = new String[] {
      "EOF",
      "error",
      "ROBOT",
      "INICIAR",
      "DETENER",
      "BASE",
      "CUERPO",
      "GARRA",
      "VELOCIDAD",
      "ABRIR_GARRA",
      "CERRAR_GARRA",
      "REPETIR",
      "PUNTO",
      "IGUAL",
      "PARENTESIS_A",
      "PARENTESIS_C",
      "LLAVE_A",
      "LLAVE_C",
      "COMA",
      "PUNTO_COMA",
      "IDENTIFICADOR",
      "NUMERO",
      "ERROR"
  };
}
